name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact:
          - ghc-200MiB
          - bazel-52MiB
          - buildozer-7MiB
          - exa-0.7MiB
        cacheEnabled:
          - false
          - true
    steps:
      - uses: actions/checkout@v3
      - name: Mount Bazel caches
        if: matrix.cacheEnabled
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel-repo
          key: bazel-cache-0-${{ matrix.artifact }}
      - name: Configure Bazel repository cache
        if: matrix.cacheEnabled
        run: |
          echo "fetch --repository_cache=~/.cache/bazel-repo" >> .bazelrc
      - name: Fetch artifact
        run: |
          bazel fetch @${{ matrix.artifact }}//file
